### ISSUE TITLE
Can't build OpenITG

### ISSUE THREAD

**Issue by Gabrimax98** [openitg/openitg#37]
I'm currently struggling with building OpenITG for Windows with LightsDriverSerial.cpp added. Using DirectX SDK June 2010 (tried also with 2007 and 2004) and Visual Studio 2008. Getting these errors: http://puu.sh/m3Gfz/5506366ceb.png
Any help would be appreciated.
Gabrimax

**Comment by terabyte** [comment]
the visual studio project files have to be updated separately on windows, but most of our devs do not run windows I think (I don't), so they probably got out of sync.  Maybe one of the devs who actually owns a windows box can check it out though...

Best bet to get help, since you have made changes, is to fork this repo and commit your changes to a branch so others can look at it, and know exactly what you have.
