### ISSUE TITLE
Prefsman issue

### ISSUE THREAD

**Issue by chrispable** [openitg/openitg#91]
This is likely MY fault...

I need to read a value the user can arbitrarily set in the ini. Code I am using always returns NULL even when set in static.ini and stepmania.ini. Type is a string.

IPreference *TEST_PREF = PREFSMAN->GetPreferenceByName("TEST_PREFERENCE");
	if( TEST_PREF == NULL )
	{
			LOG->Info("TEST PREFERENCE NOT FOUND");
	}
else
	{
		CString ctype= TEST_PREF->ToString();
		if (ctype.CompareNoCase( "val1" ))
		{
				test_bool=true;
		}
		else
		{
			test_bool=false;
		}
	}

Any guidance here? It seems like this functionality is only really used for values that is already explicitly defined, not arbitrarily.

**Comment by augustg** [comment]
Check out the implementation of GetPreferenceByName. Your IPreference must previously exist as a "subscriber" to PreferenceManager.
The constructor of Preference mutates PreferenceManager by adding itself as a subscriber. When a value is PreferenceManager in turn mutates Preference creating a circular dependency. 
This means you have new up a Preference instead of calling GetPreferenceByName. 
An example can be found in InputHandler.h. Examine how "g_bDebugInputDrivers" is used.
Also, keep in mind that all instances of Preference are populated when the game boots.

**Comment by chrispable** [comment]
Thanks for the clarification. I did try that similar syntax as a guide when I was messing around and it didn't work. I did however find the source of my problem. It has to do with the CString datatype you guys are using to abstract. The comparison always fails using the other syntax so I figured something was wrong with initializing a preference. I didn't consider the compare function to be at fault. I got around it by using the syntax you suggested and throwing a few things near the top of the file:

#include <String.h>
#if defined(_MSC_VER)
#define strcasecmp _stricmp
#endif

Then using strcasecmp with a return of c_str() on the data type. I assume it may have had something to do with wide characters or something. Thanks so much for the help!
